export interface CreatorROIInput {
  followers: number;
  engagementRate: number; // percent like 4.5
  avgReach?: number;
  pastCollabs?: number;
  contentQuality?: number; // 1-5 scale
}

export interface CreatorROIResult {
  roi: number;
  breakdown: {
    reachScore: number;
    collabScore: number;
    qualityScore: number;
  };
}

/**
 * Rough estimation of potential ROI generated by a creator.
 * Score ranges from 0 to 100.
 */
export function estimateCreatorROI(input: CreatorROIInput): CreatorROIResult {
  const reach = input.avgReach ?? (input.followers * input.engagementRate) / 100;
  const reachScore = Math.min(reach / 1000, 50); // up to 50 points
  const collabScore = Math.min((input.pastCollabs ?? 0) * 4, 20); // 4 points each
  const qualityScore = Math.min(((input.contentQuality ?? 3) / 5) * 30, 30);

  const roi = Math.round(reachScore + collabScore + qualityScore);
  return {
    roi,
    breakdown: {
      reachScore: Math.round(reachScore),
      collabScore: Math.round(collabScore),
      qualityScore: Math.round(qualityScore),
    },
  };
}
